// <auto-generated />
using MediaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaService.Migrations
{
    [DbContext(typeof(MediaServiceDbContext))]
    [Migration("20241118124425_AddSeedExampleData")]
    partial class AddSeedExampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaService.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An example book description.",
                            ImageUrl = "https://example.com/images/book.jpg",
                            MediaType = "Book",
                            Title = "Example Book"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An example DVD description.",
                            ImageUrl = "https://example.com/images/dvd.jpg",
                            MediaType = "DVD",
                            Title = "Example DVD"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An example game description.",
                            ImageUrl = "https://example.com/images/game.jpg",
                            MediaType = "Game",
                            Title = "Example Game"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
